### ISSUE TITLE
Umbraco 7.6 Initialize doesnt work

### ISSUE THREAD

**Issue by khraibani** [markwemekamp/RankOne-Umbraco-SEO-Tool#17]
When I press on Initialize I get An error has occured.
response back from getting 500 Internal Server Error
http://localhost:55968/umbraco/backoffice/rankone/RankOneApi/Initialize

Console stack trace:
ExceptionMessage:"Object reference not set to an instance of an object."
Stacktrace: at Umbraco.Core.Persistence.Database.BeginTransaction(IsolationLevel isolationLevel)
↵   at Umbraco.Core.Persistence.DatabaseSchemaHelper.CreateTable(Boolean overwrite, Type modelType)
↵   at RankOne.Controllers.RankOneApiController.Initialize()
↵   at lambda_method(Closure , Object , Object[] )
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
Name

**Comment by honzabilek4** [comment]
Hi, this issue affects me as well. It's probably connected to the Umbraco 7.6.0 update. I'm going to check the changelog and try to fix it.

**Comment by markwemekamp** [comment]
Thanks for reporting. Haven't tested it with the new version yet, I'll give it a look as soon as possible.

**Comment by markwemekamp** [comment]
This has to do with the recent changes to how Database works in Umbraco 7.6

http://issues.umbraco.org/issue/U4-9855

I've managed to reproduce this locally and hope to release a fix this week

**Comment by markwemekamp** [comment]
I've added a new version to nuget, this should fix this problem.

https://www.nuget.org/packages/RankOne?NormalizedVersion=0.3.6

**Comment by honzabilek4** [comment]
However I can't see what you've changed because the commit is huge,  it fixes the issue :). Thanks!

**Comment by markwemekamp** [comment]
My bad, accidentially checked in my Umbraco test project 
The changes are in the DashboardDataService

https://github.com/markwemekamp/RankOne-Umbraco-SEO-Tool/commits/master/src/RankOne.SEO.Tool/Services/DashboardDataService.cs

**Comment by msinnott22** [comment]
I still get this issue with the updated version.  Is there anything else I could try to get this to work? I love this package!

**Comment by markwemekamp** [comment]
I've released a new version with a hotfix on our and nuget

**Comment by khraibani** [comment]
@markwemekamp thanks, its working 💯
